apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
spec:
  destination:
    name: ''
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: dev
    repoURL: 'https://github.com/kfns0b11/argocd-demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true